### PR TITLE
chore: update to recommended raw github source for install script

### PR DESCRIPTION
**Pull request by bjohnso5**

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:5fd858fb0621e91b6574d0014c3777a524c41833

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:b526daa229ab6fe2281714820c1743211966add1

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:f04aea573aa6d2c4e1c146f6568b70436b4be7ea

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:0af425d5a870c36c6a383adb85fcfe4fca4d0771

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:82d058db9c4105dc491845f07f4da9cbd1066678

**Review by zaki-arain — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:61a26c3326d37759907edd2e6b10b89e0d3cecd5

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=dev:61a26c3326d37759907edd2e6b10b89e0d3cecd5

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/serverless-framework?version=2.0.2

**Pull request merged**
