### PR TITLE
fix: changed url of the installation script fixes #51

### LINKED ISSUE #51: Serverless Deploy failing
**Orb Version**
`circleci/serverless-framework@2.0.1`

**Describe the bug**
The "Install Serverless CLI" step is failing, following the instructions from https://circleci.com/developer/orbs/orb/circleci/serverless-framework#orb-source

**To Reproduce**

Run a serverless deploy in the CircleCI pipeline.

Our deploy config, essentially straight from the CircleCI documentation:
```
  deploy-prod:
    executor: serverless-framework/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: serverless deploy --stage prod --verbose
          name: deploy
```

**Expected behavior**

The serverless deploy executes.

**Current behavior**
Screenshot 2024-05-21 at 1 43 31 PM

**Additional context**

This was working yesterday, but started failing today. I've been informed that the Serverless team released their v4 beta today, so there may be something going on there.

Link to Serverless thread: https://forum.serverless.com/t/serverless-deploy-failing-when-run-from-circleci/20184

### PR DESCRIPTION
**Pull request by salemgolemugoo**

### CODE REVIEW

**Comment by salemgolemugoo** [comment]
@CircleCI-Public/orb-publishers could you guys review this PR. As long as the issue affects a lot of users

**Comment by salemgolemugoo** [comment]
@Jaryt @EricRibeiro @KyleTryon looks like mentioning by the team name doesn't work

**Comment by KyleTryon** [comment]
We are no longer members of the team

**Comment by bjohnso5** [comment]
Implemented in #54

**Pull request closed without merging**
