### PR TITLE
fixes path expansion

### PR DESCRIPTION
**Pull request by nyoungstudios**
The environment variables in this line are being expanded before appended to the `$BASH_ENV` file. Single quotes ensures that it won't be expanded when it is appended to the `$BASH_ENV` file.

This is the same problem as outlined here: https://github.com/CircleCI-Public/gcp-cli-orb/issues/22

A good way to check this is to ssh into the CircleCI job after doing the `serverless/setup` command. And try to run `python`. In the current situation, `python` will fail to run, but after this fix, `python` will work correctly.

(Sorry, I initially created the PR against master, but after reading the readme, I have changed it to the alpha branch)

### CODE REVIEW

**Comment by KyleTryon** [comment]
@nyoungstudios Sorry you were correct the first time, we will be modifying our process and the documentation soon. The "alpha" branch was a suggestion to orb authors (it is auto-generated) to make their changes in feature branches rather than commit directly to master.

**Comment by nyoungstudios** [comment]
@KyleTryon no problem, shall I reopen the last PR and close this one? Or were you looking to fix this merge conflicts here instead?

**Comment by KyleTryon** [comment]
> @KyleTryon no problem, shall I reopen the last PR and close this one? Or were you looking to fix this merge conflicts here instead?

Ill work with whatever is easiest for you. I imagine opening a previous PR and closing this one is easier.

**Comment by nyoungstudios** [comment]
@KyleTryon thank you, I agree. I've reopened the previous pr: https://github.com/CircleCI-Public/serverless-framework-orb/pull/12

**Pull request closed without merging**
